# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isRelease: $[eq(variables['Build.SourceBranch'], 'refs/heads/release')]
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

trigger:
  - main
  - release
  - develop

pr: none

pool:
  vmImage: 'ubuntu-20.04'

steps:
  - task: replacetokens@4
    inputs:
      targetFiles: 'applicationwebapp.yml'
      encoding: 'auto'
      tokenPattern: 'default'
      writeBOM: true
      actionOnMissing: 'continue'
      keepToken: true
      actionOnNoFiles: 'continue'
      enableTransforms: false
      useLegacyPattern: false
      enableTelemetry: true

  - task: Maven@3
    displayName: Tests and Validations
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'verify'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'

  ### BUILD DEV ARTIFACTS
  - task: Maven@3
    displayName: Build Dev Artifact
    condition: and(eq(variables.isDevelop, true), succeeded())
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      mavenOptions: -DskipTests=true
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'

  - task: PublishBuildArtifacts@1
    condition: and(eq(variables.isDevelop, true), succeeded())
    inputs:
      PathtoPublish: 'applicationwebapp.yml'
      ArtifactName: 'dev'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Dev output files'
    condition: and(eq(variables.isDevelop, true), succeeded())
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/elea-apx-ms-backend-app/target/elea-apx-ms-backend-app.jar'
      ArtifactName: 'dev'
      publishLocation: 'Container'

  ### BUILD QA ARTIFACTS
  - task: Maven@3
    displayName: Build QA Artifact
    condition: and(eq(variables.isRelease, true), succeeded())
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      mavenOptions: -DskipTests=true
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'

  - task: PublishBuildArtifacts@1
    condition: and(eq(variables.isRelease, true), succeeded())
    inputs:
      PathtoPublish: 'applicationwebapp.yml'
      ArtifactName: 'qa'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish QA output files'
    condition: and(eq(variables.isRelease, true), succeeded())
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/elea-apx-ms-backend-app/target/elea-apx-ms-backend-app.jar'
      ArtifactName: 'qa'
      publishLocation: 'Container'

    ### BUILD PROD ARTIFACTS
  - task: Maven@3
    displayName: Build PROD Artifact
    condition: and(eq(variables.isMain, true), succeeded())
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      mavenOptions: -DskipTests=true
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'

  - task: PublishBuildArtifacts@1
    condition: and(eq(variables.isMain, true), succeeded())
    inputs:
      PathtoPublish: 'applicationwebapp.yml'
      ArtifactName: 'prod'
      publishLocation: 'Container'

  - task: AzureRmWebAppDeployment@4
    enabled: false
    condition: and(eq(variables.isMain, true), succeeded())
    displayName: Deploy app
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'APx_dev'
      appType: 'webAppLinux'
      WebAppName: 'app02-dev-apx'
      packageForLinux: '/home/vsts/work/1/s/elea-apx-ms-backend-app/target/elea-apx-ms-backend-app.jar'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish PROD output files'
    condition: and(eq(variables.isMain, true), succeeded())
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/elea-apx-ms-backend-app/target/elea-apx-ms-backend-app.jar'
      ArtifactName: 'prod'
      publishLocation: 'Container'