INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/01/01' as date),'yyyy-MM-dd'),'Año Nuevo');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/02/28' as date),'yyyy-MM-dd'),'Carnaval');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/03/01' as date),'yyyy-MM-dd'),'Carnaval');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/03/24' as date),'yyyy-MM-dd'),'Día Nacional de la Memoria por la Verdad y la Justicia');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/04/02' as date),'yyyy-MM-dd'),'Día del Veterano y de los Caídos en la Guerra de Malvinas');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/04/14' as date),'yyyy-MM-dd'),'Jueves Santo');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/04/15' as date),'yyyy-MM-dd'),'Viernes Santo');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/04/16' as date),'yyyy-MM-dd'),'Primeros dos días de la Pascua Judía (b)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/04/17' as date),'yyyy-MM-dd'),'Primeros dos días de la Pascua Judía (b)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/04/22' as date),'yyyy-MM-dd'),'Últimos dos días de la Pascua Judía (b)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/04/23' as date),'yyyy-MM-dd'),'Últimos dos días de la Pascua Judía (b)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/04/24' as date),'yyyy-MM-dd'),'Día de acción por la tolerancia y el respeto entre los pueblos (a)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/05/01' as date),'yyyy-MM-dd'),'Día del Trabajador');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/05/02' as date),'yyyy-MM-dd'),'Fiesta de la Ruptura del Ayuno del Sagrado Mes de Ramadán (Id al-Fitr) (c)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/05/25' as date),'yyyy-MM-dd'),'Día de la Revolución de Mayo');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/06/17' as date),'yyyy-MM-dd'),'Paso a la Inmortalidad del Gral. Don Martín Miguel de Güemes');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/06/20' as date),'yyyy-MM-dd'),'Paso a la Inmortalidad del Gral. Manuel Belgrano');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/07/09' as date),'yyyy-MM-dd'),'Día de la Independencia ');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/07/09' as date),'yyyy-MM-dd'),'Fiesta del Sacrificio (c)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/07/30' as date),'yyyy-MM-dd'),'Año Nuevo Islámico (c)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/08/15' as date),'yyyy-MM-dd'),'Paso a la Inmortalidad del Gral. José de San Martín (17/8)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/09/26' as date),'yyyy-MM-dd'),'Año Nuevo Judío (b)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/09/27' as date),'yyyy-MM-dd'),'Año Nuevo Judío (b)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/10/05' as date),'yyyy-MM-dd'),'Día del Perdón (b)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/10/07' as date),'yyyy-MM-dd'),'Feriado con fines turísticos"');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/10/10' as date),'yyyy-MM-dd'),'Día del Respeto a la Diversidad Cultural (12/10)');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/11/20' as date),'yyyy-MM-dd'),'Día de la Soberanía Nacional');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/11/21' as date),'yyyy-MM-dd'),'Feriado con fines turísticos');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/12/08' as date),'yyyy-MM-dd'),'Inmaculada Concepción de María');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/12/09' as date),'yyyy-MM-dd'),'Feriado con fines turísticos');
INSERT INTO dias_no_laborables(fecha, nombre) values(FORMAT(CAST('2022/12/25' as date),'yyyy-MM-dd'),'Navidad');
