ALTER TABLE doctor ALTER COLUMN lugarDocente VARCHAR(256)
ALTER TABLE doctor ALTER COLUMN lugarCoordinador VARCHAR(256)
ALTER TABLE doctor ALTER COLUMN ObsLiderOpi VARCHAR(256)
ALTER TABLE doctor ALTER COLUMN obsSocieCienti VARCHAR(256)
go

